# Generated by Django 4.2.7 on 2026-02-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی'),
        ),
    ]
