# Generated by Django 4.2.7 on 2025-09-20 11:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper', '0003_paper_cub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_family', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(max_length=20, verbose_name='کد ملی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تلفن')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammage', models.FloatField(verbose_name='گراماژ')),
                ('width', models.FloatField(verbose_name='عرض')),
                ('humidity', models.FloatField(verbose_name='رطوبت')),
                ('burst', models.FloatField(verbose_name='ترکیدگی')),
                ('cub', models.FloatField(verbose_name='کاب')),
                ('md', models.FloatField(verbose_name='MD')),
                ('cd', models.FloatField(verbose_name='CD')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'مشخصات بارگیری',
                'verbose_name_plural': 'مشخصات بارگیری\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_items', models.JSONField(default=list, help_text='لیست نام فیلدهای کاغذ که کاربر برای چاپ انتخاب کرده', verbose_name='فیلدهای سفارشی انتخاب شده')),
                ('print_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد چاپ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('completed', 'تکمیل شده'), ('printed', 'چاپ شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.customer', verbose_name='مشتری')),
                ('loading_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qc.loading', verbose_name='مشخصات بارگیری')),
                ('rollnumbers', models.ManyToManyField(help_text='رکوردهای کاغذ انتخاب شده برای این کنترل کیفی', related_name='qc_records', to='paper.paper', verbose_name='شماره رول‌ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رکورد کنترل کیفی',
                'verbose_name_plural': 'رکوردهای کنترل کیفی',
                'ordering': ['-create_time'],
            },
        ),
    ]
