# Generated by Django 4.2.7 on 2025-09-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='نام کاربری')),
                ('model_name', models.CharField(max_length=100, verbose_name='نام مدل')),
                ('action_type', models.CharField(choices=[('create', 'ایجاد'), ('edit', 'ویرایش'), ('delete', 'حذف')], max_length=10, verbose_name='نوع عملیات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name': 'ورودی لاگ',
                'verbose_name_plural': 'ورودی\u200cهای لاگ',
                'ordering': ['-timestamp'],
            },
        ),
    ]
