# Generated by Django 4.2.7 on 2026-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_logentry_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='جزئیات'),
        ),
    ]
