# Generated by Django 4.2.7 on 2026-05-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_plckey_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plckey',
            name='key',
            field=models.CharField(max_length=50, verbose_name='کلید'),
        ),
    ]
