# Generated by Django 4.2.7 on 2026-05-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_plckey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plckey',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
    ]
