# Generated by Django 4.2.7 on 2025-10-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0007_alter_probeconfiguration_checked_probes'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeconfiguration',
            name='humidity_threshold',
            field=models.FloatField(default=7),
        ),
    ]
