# Generated by Django 4.2.7 on 2025-12-23 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_type', '0001_initial'),
        ('paper', '0008_pm_setting_cylinder_temperature_after_press_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='PaperType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='paper_type.papertype', verbose_name='نوع کاغذ'),
        ),
    ]
