# Generated by Django 4.2.7 on 2026-01-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0011_remove_paper_cylinder_temperature_after_press_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_setting',
            name='paper_temperature_before_pop_reel',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای کاغذ قبل از پوپ ریل'),
        ),
        migrations.AddField(
            model_name='pm_setting',
            name='paper_temperature_before_starch',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای کاغذ قبل از نشاسته'),
        ),
    ]
