# Generated by Django 4.2.7 on 2026-02-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام فارسی')),
                ('en_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام انگلیسی')),
                ('order_index', models.IntegerField(blank=True, null=True, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'نام درایو',
                'verbose_name_plural': 'نام\u200cهای درایو',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speed', models.IntegerField(blank=True, null=True, verbose_name='سرعت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('Drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeds', to='speed.drivenames', verbose_name='درایو')),
            ],
            options={
                'verbose_name': 'سرعت',
                'verbose_name_plural': 'سرعت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
