# Generated by Django 4.2.7 on 2026-02-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speed',
            old_name='Speed',
            new_name='Speed1',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Drive',
        ),
        migrations.AddField(
            model_name='speed',
            name='BOT_Fan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='BOT_Pressure_Screen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='BOT_Wire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Baby_Roll',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Bot_Vacum_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Bot_Vacum_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Calendar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Dryer_1_Bottom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Dryer_1_Top',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Dryer_2_Bottom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Dryer_2_Top',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Dryer_3_Bottom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Dryer_3_Top',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Felt_Vac_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Felt_Vac_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='HeadBox_Water_Pump',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Post_Dryer_Bottom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Post_Dryer_Top',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Press_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Press_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Press_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Reel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Roll_Number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='رول شماره'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Size_Press',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed10',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed11',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed12',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed13',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed14',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed15',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed16',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed17',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed18',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed19',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed2',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed20',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed21',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed22',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed23',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed24',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed25',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed26',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed27',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed28',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed3',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed4',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed5',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed6',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed7',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed8',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='Speed9',
            field=models.IntegerField(blank=True, null=True, verbose_name='سرعت'),
        ),
        migrations.AddField(
            model_name='speed',
            name='TOP_WIRE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Top_Fan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Top_Pressure_Screen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Top_Pulp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speed',
            name='Top_Vacuum_Wire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DriveNames',
        ),
    ]
