# Generated by Django 4.2.7 on 2025-12-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_paper_density_valve2_paper_density_valve3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_setting',
            name='cylinder_temperature_after_press',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای سیلندر بعد از سایز پرس'),
        ),
        migrations.AddField(
            model_name='pm_setting',
            name='cylinder_temperature_before_press',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای سیلندر قبل از سایز پرس'),
        ),
    ]
