# Generated by Django 4.2.7 on 2025-10-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_paper_productionline'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='CauseOfTearing',
            field=models.CharField(blank=True, max_length=250, verbose_name='علت پارگی/توقف'),
        ),
        migrations.AddField(
            model_name='paper',
            name='ProductionDowntime',
            field=models.CharField(blank=True, max_length=50, verbose_name='زمان وقفه در تولید ( دقیقه )'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='ash_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='ash'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='burst_test',
            field=models.TextField(blank=True, verbose_name='burst'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='density_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='شیر غلظت'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='عرض کاغذ'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='real_grammage',
            field=models.FloatField(blank=True, null=True, verbose_name='گراماژ'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tensile_strength_cd',
            field=models.FloatField(blank=True, null=True, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tensile_strength_md',
            field=models.FloatField(blank=True, null=True, verbose_name='MD'),
        ),
    ]
