# Generated by Django 4.2.7 on 2025-09-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='ash',
            field=models.FloatField(blank=True, null=True, verbose_name='خاکستر'),
        ),
        migrations.AddField(
            model_name='loading',
            name='custom',
            field=models.BooleanField(default=False, verbose_name='سفارشی'),
        ),
        migrations.AlterField(
            model_name='loading',
            name='burst',
            field=models.FloatField(blank=True, null=True, verbose_name='burst'),
        ),
        migrations.AlterField(
            model_name='loading',
            name='cd',
            field=models.FloatField(blank=True, null=True, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='loading',
            name='cub',
            field=models.FloatField(blank=True, null=True, verbose_name='کاب'),
        ),
        migrations.AlterField(
            model_name='loading',
            name='md',
            field=models.FloatField(blank=True, null=True, verbose_name='MD'),
        ),
    ]
