# Generated by Django 4.2.7 on 2025-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='type',
            field=models.CharField(choices=[('ph', 'pH'), ('moisture', 'رطوبت'), ('burst', 'ترکیدگی'), ('rct', 'RCT'), ('cct', 'CCT'), ('md', 'MD'), ('cd', 'CD'), ('gms', 'گراماژ'), ('cub', 'کاب')], max_length=20, verbose_name='نوع داده'),
        ),
    ]
