# Generated by Django 4.2.7 on 2025-09-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulp',
            name='downpulpcount',
            field=models.FloatField(blank=True, null=True, verbose_name='count خمیر پایین'),
        ),
    ]
