# Generated by Django 4.2.7 on 2026-02-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='update_details',
            field=models.TextField(blank=True, null=True, verbose_name='جزئیات آپدیت'),
        ),
    ]
