# Generated by Django 4.2.7 on 2025-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0006_add_checked_probes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probeconfiguration',
            name='checked_probes',
            field=models.JSONField(default=list),
        ),
    ]
