# Generated by Django 4.2.7 on 2025-09-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_formula', models.TextField()),
                ('probe_count', models.IntegerField(default=0)),
                ('probes_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
