# Generated by Django 4.2.7 on 2025-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0002_probeconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probeconfiguration',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='probeconfiguration',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='probedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
