# Generated by Django 4.2.7 on 2025-11-25 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_paper_causeoftearing_paper_productiondowntime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'ماشین تولید',
                'verbose_name_plural': 'ماشین\u200cهای تولید',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='paper',
            name='ash_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Ash'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='burst_test',
            field=models.TextField(blank=True, verbose_name='Burst'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='cub',
            field=models.FloatField(blank=True, null=True, verbose_name='CUB'),
        ),
        migrations.CreateModel(
            name='PM_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom', models.CharField(blank=True, max_length=200, verbose_name='شیر خمیر هدباکس پایین')),
                ('top', models.CharField(blank=True, max_length=200, verbose_name='شیر خمیر هدباکس بالا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_settings', to='paper.paper', verbose_name='رکورد کاغذ')),
                ('production_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_settings', to='paper.productionmachine', verbose_name='ماشین تولید')),
            ],
            options={
                'verbose_name': 'تنظیمات ماشین تولید',
                'verbose_name_plural': 'تنظیمات ماشین\u200cهای تولید',
                'ordering': ['production_machine__title'],
                'unique_together': {('paper', 'production_machine')},
            },
        ),
    ]
