# Generated by Django 4.2.7 on 2025-12-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0010_remove_paper_paper_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='cylinder_temperature_after_press',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='cylinder_temperature_before_press',
        ),
    ]
