# Generated by Django 4.2.7 on 2025-09-03 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ')),
                ('sampling_start_time', models.CharField(max_length=5, verbose_name='زمان شروع نمونه\u200cگیری')),
                ('sampling_end_time', models.CharField(max_length=5, verbose_name='زمان پایان نمونه\u200cگیری')),
                ('roll_number', models.CharField(max_length=50, verbose_name='شماره رول')),
                ('responsible_person_name', models.CharField(max_length=200, verbose_name='نام مسئول')),
                ('shift', models.CharField(blank=True, choices=[('day', 'روزانه'), ('night', 'شبانه')], max_length=10, null=True, verbose_name='شیفت')),
                ('paper_type', models.CharField(blank=True, choices=[('test_liner', 'تست لاینر'), ('float', 'فلوت'), ('white_top_test_liner', 'تست لاینر سفید')], max_length=30, null=True, verbose_name='نوع کاغذ')),
                ('paper_size', models.IntegerField(blank=True, null=True, verbose_name='اندازه کاغذ')),
                ('NumberOfTears', models.IntegerField(blank=True, null=True, verbose_name='تعداد پارگی')),
                ('real_grammage', models.FloatField(blank=True, null=True, verbose_name='گراماژ واقعی')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='رطوبت')),
                ('ash_percentage', models.FloatField(blank=True, null=True, verbose_name='درصد خاکستر')),
                ('profile', models.CharField(blank=True, choices=[('1', '+۱g-'), ('2', '+۲g-'), ('3', '+۳g-'), ('4', '+۴g-'), ('5', 'بیشتر از 5 گرم نوسان سر تا سر کاغذ')], max_length=10, null=True, verbose_name='پروفایل')),
                ('density_valve', models.FloatField(blank=True, null=True, verbose_name='شیر چگالی')),
                ('diluting_valve', models.FloatField(blank=True, null=True, verbose_name='شیر رقیق\u200cساز')),
                ('cylinder_temperature_before_press', models.FloatField(blank=True, null=True, verbose_name='دمای سیلندر قبل از سایز پرس')),
                ('cylinder_temperature_after_press', models.FloatField(blank=True, null=True, verbose_name='دمای سیلندر بعد از سایز پرس')),
                ('burst_test', models.TextField(blank=True, verbose_name='تست ترکیدگی')),
                ('tensile_strength_md', models.FloatField(blank=True, null=True, verbose_name='مقاومت کششی MD')),
                ('tensile_strength_cd', models.FloatField(blank=True, null=True, verbose_name='مقاومت کششی CD')),
                ('cct1', models.FloatField(blank=True, null=True, verbose_name='CCT 1')),
                ('cct2', models.FloatField(blank=True, null=True, verbose_name='CCT 2')),
                ('cct3', models.FloatField(blank=True, null=True, verbose_name='CCT 3')),
                ('cct4', models.FloatField(blank=True, null=True, verbose_name='CCT 4')),
                ('cct5', models.FloatField(blank=True, null=True, verbose_name='CCT 5')),
                ('rct1', models.FloatField(blank=True, null=True, verbose_name='RCT 1')),
                ('rct2', models.FloatField(blank=True, null=True, verbose_name='RCT 2')),
                ('rct3', models.FloatField(blank=True, null=True, verbose_name='RCT 3')),
                ('rct4', models.FloatField(blank=True, null=True, verbose_name='RCT 4')),
                ('rct5', models.FloatField(blank=True, null=True, verbose_name='RCT 5')),
                ('tearing_time', models.CharField(blank=True, max_length=5, verbose_name='زمان پارگی')),
                ('calender_applied', models.BooleanField(default=False, verbose_name='کلندر اعمال شده')),
                ('machine_speed', models.FloatField(blank=True, null=True, verbose_name='سرعت دستگاه')),
                ('material_usage', models.TextField(blank=True, verbose_name='مصرف مواد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رکورد کاغذ',
                'verbose_name_plural': 'رکوردهای کاغذ',
                'ordering': ['-created_at'],
            },
        ),
    ]
