# Generated by Django 4.2.7 on 2026-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0013_paper_profile_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_setting',
            name='dryer3_first_cylinder_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای سیلندر اول خشک کن سه'),
        ),
        migrations.AddField(
            model_name='pm_setting',
            name='fructose_temperature_before_press',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای نشاسته قبل از ورودی سایز پرس'),
        ),
        migrations.AddField(
            model_name='pm_setting',
            name='paper_temperature_before_dryer3',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای کاغذ قبل از ورود به خشک کن سه'),
        ),
        migrations.AlterField(
            model_name='pm_setting',
            name='cylinder_temperature_after_press',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای اصلی خشک کن سه'),
        ),
        migrations.AlterField(
            model_name='pm_setting',
            name='cylinder_temperature_before_press',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای اصلی خشک کن یک و دو'),
        ),
        migrations.AlterField(
            model_name='pm_setting',
            name='paper_temperature_before_starch',
            field=models.FloatField(blank=True, null=True, verbose_name='دمای کاغذ قبل از ورود به سایز پرس'),
        ),
    ]
