# Generated by Django 4.2.7 on 2026-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0014_pm_setting_dryer3_first_cylinder_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_setting',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='جزئیات'),
        ),
    ]
