# Generated by Django 4.2.7 on 2026-02-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0016_paper_is_delete_productionmachine_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='burst_test',
            field=models.TextField(blank=True, null=True, verbose_name='Burst'),
        ),
    ]
