# Generated by Django 4.2.7 on 2026-05-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0017_alter_paper_burst_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='warehouse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='انبار'),
        ),
    ]
