# Generated by Django 4.2.7 on 2025-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0004_alter_probeconfiguration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probeconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='probeconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='probedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
