# Generated by Django 4.2.7 on 2025-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ')),
                ('type', models.CharField(choices=[('ph', 'pH'), ('moisture', 'رطوبت'), ('burst', 'ترکیدگی'), ('rct', 'RCT'), ('md', 'MD'), ('cd', 'CD')], max_length=20, verbose_name='نوع داده')),
                ('value', models.CharField(max_length=20, verbose_name='مقدار')),
                ('roll_number', models.CharField(max_length=50, verbose_name='شماره رول')),
                ('start_time', models.CharField(max_length=5, verbose_name='زمان شروع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'داده نمودار',
                'verbose_name_plural': 'داده\u200cهای نمودار',
                'ordering': ['-date', '-start_time'],
                'unique_together': {('date', 'type', 'roll_number')},
            },
        ),
    ]
