# Generated by Django 4.2.7 on 2026-01-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_plckey_rollplcdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCColumnPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_keys', models.JSONField(blank=True, default=list, verbose_name='کلیدهای قابل نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیم ستون\u200cهای PLC',
                'verbose_name_plural': 'تنظیمات ستون\u200cهای PLC',
            },
        ),
    ]
