# Generated by Django 4.2.7 on 2025-10-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0008_probeconfiguration_humidity_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='probedata',
            name='roll_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
