# Generated by Django 4.2.7 on 2025-10-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0009_probedata_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeconfiguration',
            name='roll_number',
            field=models.IntegerField(blank=True, default=3830, null=True),
        ),
        migrations.AddField(
            model_name='probeconfiguration',
            name='roll_remainder',
            field=models.IntegerField(blank=True, default=2400, null=True),
        ),
    ]
