# Generated by Django 4.2.7 on 2025-10-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0010_probeconfiguration_roll_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeconfiguration',
            name='edge_threshold',
            field=models.FloatField(default=5),
        ),
    ]
