# Generated by Django 4.2.7 on 2025-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0011_probeconfiguration_edge_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeconfiguration',
            name='roll_Duration',
            field=models.IntegerField(blank=True, default=2400, null=True),
        ),
    ]
