# Generated by Django 4.2.7 on 2025-10-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0012_probeconfiguration_roll_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeconfiguration',
            name='is_user_allowed_auto_change_roll_number',
            field=models.BooleanField(default=False),
        ),
    ]
