# Generated by Django 4.2.7 on 2025-10-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermal', '0013_probeconfiguration_is_user_allowed_auto_change_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='probeconfiguration',
            name='auto_edge_detection',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='probeconfiguration',
            name='roll_remainder',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
