# Generated by Django 4.2.7 on 2026-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='جزئیات'),
        ),
    ]
