# Generated by Django 4.2.7 on 2025-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp', '0003_pulp_productionline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulp',
            name='downpulpfreenes',
        ),
        migrations.AlterField(
            model_name='pulp',
            name='downpulpcount',
            field=models.FloatField(blank=True, null=True, verbose_name='کانس خمیر پایین'),
        ),
        migrations.AlterField(
            model_name='pulp',
            name='lower_headbox_freeness',
            field=models.FloatField(blank=True, null=True, verbose_name='فرینس خمیر پایین'),
        ),
    ]
