# Generated by Django 4.2.7 on 2025-11-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulp', '0004_remove_pulp_downpulpfreenes_alter_pulp_downpulpcount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pulp_Sampling_Location_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'نام محل نمونه\u200cگیری خمیر',
                'verbose_name_plural': 'نام\u200cهای محل نمونه\u200cگیری خمیر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pulp',
            name='curtain_consistency',
            field=models.FloatField(blank=True, null=True, verbose_name='کانس کردان'),
        ),
        migrations.AlterField(
            model_name='pulp',
            name='pond8_consistency',
            field=models.FloatField(blank=True, null=True, verbose_name='کانس حوض 8'),
        ),
        migrations.AlterField(
            model_name='pulp',
            name='thickener_consistency',
            field=models.FloatField(blank=True, null=True, verbose_name='کانس تیکنر'),
        ),
        migrations.AlterField(
            model_name='pulp',
            name='upper_headbox_freeness',
            field=models.FloatField(blank=True, null=True, verbose_name='فرینس هدباکس بالا'),
        ),
        migrations.CreateModel(
            name='pulp_Sampling_Location_vals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('value', models.CharField(blank=True, max_length=255, verbose_name='مقدار')),
                ('pulp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_locations', to='pulp.pulp', verbose_name='خمیر')),
            ],
            options={
                'verbose_name': 'مقدار محل نمونه\u200cگیری خمیر',
                'verbose_name_plural': 'مقادیر محل نمونه\u200cگیری خمیر',
                'ordering': ['-id'],
            },
        ),
    ]
