# Generated by Django 4.2.7 on 2026-02-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_allowed_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_updating',
            field=models.BooleanField(default=False, verbose_name='در حال به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updating_message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام به\u200cروزرسانی'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updating_timer_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='تایمر (ثانیه)'),
        ),
    ]
