# Generated by Django 4.2.7 on 2026-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_chartdata_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLCKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True, verbose_name='شناسه خارجی')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('fa_name', models.CharField(max_length=255, verbose_name='نام فارسی')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='کلید')),
                ('value_type', models.CharField(blank=True, max_length=50, verbose_name='نوع مقدار')),
                ('order_index', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('creation_datetime', models.FloatField(blank=True, null=True, verbose_name='زمان ایجاد (سیستم خارجی)')),
                ('last_update', models.FloatField(blank=True, null=True, verbose_name='آخرین بروزرسانی (سیستم خارجی)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'کلید PLC',
                'verbose_name_plural': 'کلیدهای PLC',
                'ordering': ['order_index', 'fa_name'],
            },
        ),
        migrations.CreateModel(
            name='RollPLCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50, unique=True, verbose_name='شماره رول')),
                ('plc_setting', models.JSONField(verbose_name='تنظیمات PLC')),
                ('creation_datetime', models.FloatField(blank=True, null=True, verbose_name='CreationDateTime')),
                ('paper_breaks', models.IntegerField(blank=True, null=True, verbose_name='Paper_breaks')),
                ('printed_length', models.FloatField(blank=True, null=True, verbose_name='Printed_length')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'داده PLC رول',
                'verbose_name_plural': 'داده\u200cهای PLC رول',
                'ordering': ['-created_at'],
            },
        ),
    ]
