# Generated by Django 4.2.7 on 2026-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_plccolumnpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plckey',
            name='external_id',
            field=models.IntegerField(verbose_name='شناسه خارجی'),
        ),
    ]
