# Generated by Django 4.2.7 on 2025-11-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0006_productionmachine_alter_paper_ash_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='density_valve2',
            field=models.FloatField(blank=True, null=True, verbose_name='غلظت سنج 2'),
        ),
        migrations.AddField(
            model_name='paper',
            name='density_valve3',
            field=models.FloatField(blank=True, null=True, verbose_name='غلظت سنج 3'),
        ),
        migrations.AddField(
            model_name='paper',
            name='density_valve4',
            field=models.FloatField(blank=True, null=True, verbose_name='غلظت سنج 4'),
        ),
        migrations.AddField(
            model_name='paper',
            name='density_valve5',
            field=models.FloatField(blank=True, null=True, verbose_name='غلظت سنج 5'),
        ),
        migrations.AddField(
            model_name='paper',
            name='diluting_valve2',
            field=models.FloatField(blank=True, null=True, verbose_name='رقیق کننده غلظت سنج 2'),
        ),
        migrations.AddField(
            model_name='paper',
            name='diluting_valve3',
            field=models.FloatField(blank=True, null=True, verbose_name='رقیق کننده غلظت سنج 3'),
        ),
        migrations.AddField(
            model_name='paper',
            name='diluting_valve4',
            field=models.FloatField(blank=True, null=True, verbose_name='رقیق کننده غلظت سنج 4'),
        ),
        migrations.AddField(
            model_name='paper',
            name='diluting_valve5',
            field=models.FloatField(blank=True, null=True, verbose_name='رقیق کننده غلظت سنج 5'),
        ),
    ]
