# Generated by Django 4.2.7 on 2025-12-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0009_paper_papertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='paper_type',
        ),
    ]
