# Generated by Django 4.2.7 on 2025-11-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_loading_ash_loading_custom_alter_loading_burst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcrecord',
            name='column_order',
            field=models.JSONField(blank=True, default=list, help_text='ترتیب ستون\u200cهای جدول چاپ که کاربر تنظیم کرده است', null=True, verbose_name='ترتیب ستون\u200cهای جدول چاپ'),
        ),
        migrations.AlterField(
            model_name='loading',
            name='ash',
            field=models.FloatField(blank=True, null=True, verbose_name='خاکستر (Ash)'),
        ),
    ]
