# Generated by Django 4.2.7 on 2026-02-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_systemsettings_update_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=None, help_text='لیست صفحات مجاز برای کاربر. اگر خالی باشد، دسترسی به همه صفحات دارد.', null=True, verbose_name='صفحات مجاز'),
        ),
    ]
