# Generated by Django 4.2.7 on 2025-09-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pulp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField(blank=True, null=True, verbose_name='شماره رول')),
                ('lower_sampling_time', models.CharField(blank=True, max_length=5, verbose_name='زمان نمونه\u200cگیری پایین')),
                ('downpulpcount', models.IntegerField(blank=True, null=True, verbose_name='count خمیر پایین')),
                ('downpulpfreenes', models.FloatField(blank=True, null=True, verbose_name='فرینس خمیر پایین')),
                ('lower_headbox_freeness', models.FloatField(blank=True, null=True, verbose_name='آزادی هدباکس پایین')),
                ('lower_ph', models.FloatField(blank=True, null=True, verbose_name='pH پایین')),
                ('lower_pulp_temperature', models.FloatField(blank=True, null=True, verbose_name='دمای خمیر پایین')),
                ('lower_water_filter', models.FloatField(blank=True, null=True, verbose_name='فیلتر آب پایین')),
                ('upper_headbox_consistency', models.FloatField(blank=True, null=True, verbose_name='غلظت هدباکس بالا')),
                ('upper_headbox_freeness', models.FloatField(blank=True, null=True, verbose_name='آزادی هدباکس بالا')),
                ('upper_ph', models.FloatField(blank=True, null=True, verbose_name='pH بالا')),
                ('upper_pulp_temperature', models.FloatField(blank=True, null=True, verbose_name='دمای خمیر بالا')),
                ('upper_water_filter', models.FloatField(blank=True, null=True, verbose_name='فیلتر آب بالا')),
                ('pond8_consistency', models.FloatField(blank=True, null=True, verbose_name='غلظت استخر ۸')),
                ('curtain_consistency', models.FloatField(blank=True, null=True, verbose_name='غلظت پرده')),
                ('thickener_consistency', models.FloatField(blank=True, null=True, verbose_name='غلظت غلیظ\u200cکن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'نمونه خمیر',
                'verbose_name_plural': 'نمونه\u200cهای خمیر',
                'ordering': ['-created_at'],
            },
        ),
    ]
