# Generated by Django 4.2.7 on 2026-02-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0002_rename_speed_speed_speed1_remove_speed_drive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speed',
            name='BOT_Fan',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='BOT_Pressure_Screen',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='BOT_Wire',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Baby_Roll',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Bot_Vacum_1',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Bot_Vacum_2',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Calendar',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Dryer_1_Bottom',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Dryer_1_Top',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Dryer_2_Bottom',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Dryer_2_Top',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Dryer_3_Bottom',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Dryer_3_Top',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Felt_Vac_1',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Felt_Vac_2',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='HeadBox_Water_Pump',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Post_Dryer_Bottom',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Post_Dryer_Top',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Press_1',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Press_2',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Press_3',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Reel',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Size_Press',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='TOP_WIRE',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Top_Fan',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Top_Pressure_Screen',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Top_Pulp',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Top_Vacuum_Wire',
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed1',
            field=models.IntegerField(blank=True, null=True, verbose_name='TOP_WIRE'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bot_Vacum_1'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bot_Vacum_2'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Press_1'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Press_2'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed14',
            field=models.IntegerField(blank=True, null=True, verbose_name='Press_3'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Felt_Vac_1'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed16',
            field=models.IntegerField(blank=True, null=True, verbose_name='Felt_Vac_2'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed17',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dryer_1_Top'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed18',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dryer_1_Bottom'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed19',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dryer_2_Top'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top_Pressure_Screen'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed20',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dryer_2_Bottom'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed21',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size_Press'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed22',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baby_Roll'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed23',
            field=models.IntegerField(blank=True, null=True, verbose_name='Post_Dryer_Top'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Post_Dryer_Bottom'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed25',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calendar'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed26',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reel'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed27',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dryer_3_Top'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed28',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dryer_3_Bottom'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top_Fan'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top_Pulp'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top_Vacuum_Wire'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed6',
            field=models.IntegerField(blank=True, null=True, verbose_name='HeadBox_Water_Pump'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed7',
            field=models.IntegerField(blank=True, null=True, verbose_name='BOT_Wire'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed8',
            field=models.IntegerField(blank=True, null=True, verbose_name='BOT_Pressure_Screen'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='Speed9',
            field=models.IntegerField(blank=True, null=True, verbose_name='BOT_Fan'),
        ),
    ]
