# Generated by Django 4.2.7 on 2026-02-15 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0003_remove_speed_bot_fan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speed',
            name='Speed27',
        ),
        migrations.RemoveField(
            model_name='speed',
            name='Speed28',
        ),
        migrations.AlterField(
            model_name='speed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخرین بروزرسانی'),
        ),
    ]
