# Generated by Django 4.2.7 on 2025-09-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_alter_paper_tearing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='cub',
            field=models.FloatField(blank=True, null=True, verbose_name='کاب'),
        ),
    ]
