# Generated by Django 4.2.7 on 2026-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0012_pm_setting_paper_temperature_before_pop_reel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='profile_details',
            field=models.JSONField(blank=True, null=True, verbose_name='جزئیات پروفایل'),
        ),
    ]
